// 36 cadernos reais. image: path relativo a /public (Vite serve como raiz).
// null = sem imagem ainda, CharactersSection usa emoji como fallback.
export const CHARACTERS = [
  { id: 1,  name: 'Lilo & Stitch',      image: '/cadernos/lilo.png',        emoji: '🌺' },
  { id: 2,  name: 'Patrulha Canina',    image: '/cadernos/patrulha.png',    emoji: '🐾' },
  { id: 3,  name: 'Sonic',              image: '/cadernos/sonic.png',        emoji: '💨' },
  { id: 4,  name: 'Homem-Aranha',       image: '/cadernos/homem-aranha.png', emoji: '🕷️' },
  { id: 5,  name: 'Barbie',             image: '/cadernos/barbie.png',       emoji: '💖' },
  { id: 6,  name: 'Moana',              image: '/cadernos/moana.png',        emoji: '🌊' },
  { id: 7,  name: 'Hello Kitty',        image: '/cadernos/hello-kitty.png',  emoji: '🎀' },
  { id: 8,  name: 'Pokémon',            image: '/cadernos/pokemon.png',      emoji: '⚡' },
  { id: 9,  name: 'Labubu',             image: '/cadernos/labubu.png',       emoji: '🐰' },
  { id: 10, name: 'Minecraft',          image: '/cadernos/minecraft.png',    emoji: '⛏️' },
  { id: 11, name: 'Turma da Mônica',    image: '/cadernos/monica.png',       emoji: '🐰' },
  { id: 12, name: 'LOL Surprise',       image: '/cadernos/lol.png',          emoji: '🎀' },
  { id: 13, name: 'Kung Fu Panda',      image: '/cadernos/panda.jpg',        emoji: '🐼' },
  { id: 14, name: 'Capivara',           image: '/cadernos/capivara.png',     emoji: '🦫' },
  { id: 15, name: 'Show da Luna',       image: '/cadernos/luna.png',         emoji: '🔭' },
  { id: 16, name: 'Unicórnio',          image: '/cadernos/unicornio.png',    emoji: '🦄' },
  { id: 17, name: 'Bichinhos',          image: null,                         emoji: '🐾' },
  { id: 18, name: 'Dinossauros',        image: null,                         emoji: '🦕' },
  { id: 19, name: 'Harry Potter',       image: null,                         emoji: '⚡' },
  { id: 20, name: 'Princesas',          image: null,                         emoji: '👑' },
  { id: 21, name: 'Kawaii',             image: null,                         emoji: '🌸' },
  { id: 22, name: 'Arco-íris',          image: null,                         emoji: '🌈' },
  { id: 23, name: 'Casa Mágica da Gaby',image: null,                         emoji: '🏠' },
  { id: 24, name: 'Aniversário',        image: null,                         emoji: '🎂' },
  { id: 25, name: 'Natal',              image: null,                         emoji: '🎄' },
  { id: 26, name: 'Lucas Neto',         image: null,                         emoji: '🎬' },
  { id: 27, name: 'Luluca',             image: null,                         emoji: '🎵' },
  { id: 28, name: 'Mundo Bita',         image: null,                         emoji: '🎶' },
  { id: 29, name: 'Divertidamente',     image: null,                         emoji: '😊' },
  { id: 30, name: 'Jesus',             image: null,                         emoji: '✝️' },
  { id: 31, name: 'Bíblico',            image: null,                         emoji: '📖' },
  { id: 32, name: 'Carros',             image: null,                         emoji: '🚗' },
  { id: 33, name: 'Ursinhos',           image: null,                         emoji: '🧸' },
  { id: 34, name: 'Alfabetização',      image: null,                         emoji: '🔤' },
  { id: 35, name: 'Panda',              image: null,                         emoji: '🐼' },
  { id: 36, name: 'Super-Heróis',       image: null,                         emoji: '🦸' },
]

// Os 16 cadernos com imagem real, usados na grade principal da CharactersSection
export const FEATURED_CHARACTERS = CHARACTERS.filter(c => c.image !== null)
