// 30 cadernos distribuídos pelos 9 temas do produto.
// `image: null` — substituir pelo import da arte real quando disponível.
export const CHARACTERS = [
  { id: 1, name: 'Frozen Vol. 1', emoji: '❄️', bg: 'bg-sky-400', image: null },
  { id: 2, name: 'Frozen Vol. 2', emoji: '⛄', bg: 'bg-sky-500', image: null },
  { id: 3, name: 'Frozen Vol. 3', emoji: '👑', bg: 'bg-cyan-400', image: null },
  { id: 4, name: 'Frozen Vol. 4', emoji: '🏔️', bg: 'bg-blue-400', image: null },
  { id: 5, name: 'Barbie Vol. 1', emoji: '💖', bg: 'bg-fuchsia-500', image: null },
  { id: 6, name: 'Barbie Vol. 2', emoji: '👗', bg: 'bg-pink-500', image: null },
  { id: 7, name: 'Barbie Vol. 3', emoji: '💅', bg: 'bg-fuchsia-400', image: null },
  { id: 8, name: 'Barbie Vol. 4', emoji: '🦄', bg: 'bg-pink-400', image: null },
  { id: 9, name: 'Peppa Pig Vol. 1', emoji: '🐷', bg: 'bg-brand-pink', image: null },
  { id: 10, name: 'Peppa Pig Vol. 2', emoji: '🐽', bg: 'bg-rose-400', image: null },
  { id: 11, name: 'Peppa Pig Vol. 3', emoji: '🌧️', bg: 'bg-rose-500', image: null },
  { id: 12, name: 'Peppa Pig Vol. 4', emoji: '🛝', bg: 'bg-pink-300', image: null },
  { id: 13, name: 'Moana Vol. 1', emoji: '🌊', bg: 'bg-teal-500', image: null },
  { id: 14, name: 'Moana Vol. 2', emoji: '🏝️', bg: 'bg-emerald-400', image: null },
  { id: 15, name: 'Moana Vol. 3', emoji: '⛵', bg: 'bg-teal-400', image: null },
  { id: 16, name: 'Turma da Mônica Vol. 1', emoji: '🐰', bg: 'bg-red-500', image: null },
  { id: 17, name: 'Turma da Mônica Vol. 2', emoji: '🍉', bg: 'bg-green-500', image: null },
  { id: 18, name: 'Turma da Mônica Vol. 3', emoji: '🦷', bg: 'bg-yellow-400', image: null },
  { id: 19, name: 'Turma da Mônica Vol. 4', emoji: '🐶', bg: 'bg-red-400', image: null },
  { id: 20, name: 'Lol Surprise Vol. 1', emoji: '🎀', bg: 'bg-purple-400', image: null },
  { id: 21, name: 'Lol Surprise Vol. 2', emoji: '✨', bg: 'bg-violet-500', image: null },
  { id: 22, name: 'Lol Surprise Vol. 3', emoji: '🎁', bg: 'bg-purple-500', image: null },
  { id: 23, name: 'Stitch Vol. 1', emoji: '👽', bg: 'bg-blue-600', image: null },
  { id: 24, name: 'Stitch Vol. 2', emoji: '🌺', bg: 'bg-indigo-500', image: null },
  { id: 25, name: 'Stitch Vol. 3', emoji: '🏄', bg: 'bg-blue-500', image: null },
  { id: 26, name: 'Show da Luna Vol. 1', emoji: '🔭', bg: 'bg-brand-orange', image: null },
  { id: 27, name: 'Show da Luna Vol. 2', emoji: '🧪', bg: 'bg-orange-400', image: null },
  { id: 28, name: 'Show da Luna Vol. 3', emoji: '🌙', bg: 'bg-amber-500', image: null },
  { id: 29, name: 'Arco-íris Vol. 1', emoji: '🌈', bg: 'bg-brand-purple', image: null },
  { id: 30, name: 'Arco-íris Vol. 2', emoji: '🎨', bg: 'bg-violet-400', image: null },
]
